services:
  - type: web
    name: petshop
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: MONGO_URI
        sync: false
##: JWT_SECRET
#enerateValue: true
#key: JWT_EXPIRES_IN
#alue: "id"
#key: BCRYPT_SALT_ROUNDS
##lue: "10"
